# Generated by Django 4.2.3 on 2023-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("SP", "Спорт"),
                    ("POL", "Политика"),
                    ("ECO", "Экономика"),
                    ("SOC", "Общество"),
                ],
                default="SOC",
                max_length=3,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="image.jpg",
                upload_to="uploads/posts",
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Статус публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
