# Generated by Django 4.2.3 on 2023-07-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_category_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
    ]
